config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  post 'pages/home'
  get 'pages/search_tweets'
  post 'pages/search_tweets'
  get 'pages/index'
  get 'pages/result'
  post 'pages/result'
  get 'pages/charts'
  post 'pages/charts'

   root 'pages#index'

end

app/views/pages/charts.html.erb
<%= provide(:title, "Data Statistics") %>

<%= render "layouts/header_others" %>

<!-- start Stat Section -->
<section id="stat_sec">
<div class="container">
	<div class="row">
    <br/><br/>
		<div class="title_sec">
				<h1>DATA STATISTICS</h1>
				<h2>WE’RE TWITTER FACTCHECKER GROUP FROM INSA RENNES</h2>
		</div>	
		<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
			<div class="counting_sl">
			<i class="fa fa-clock-o"></i>
			<h2 class="counter"><%= number_with_precision($stats[:propagation_time_value], precision: 2, separator: '.', delimiter: ',')%></h2>
			<h4>Propagation <%= write_time_unit($stats[:propagation_time_unit]) %></h4>
			</div>
		</div>			
		<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
			<div class="counting_sl">
			<i class="fa fa-group"></i>
			<h2 class="counter"><%= number_with_precision($stats[:touched_people], precision: 0, separator: '.', delimiter: ',')%></h2>
			<h4>Impacted Persons</h4>	
			</div>
		</div>			
		<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
			<div class="counting_sl">
			<i class="fa fa-thumbs-o-up"></i>
			<h2 class="counter"><%= number_with_precision($stats[:favs], precision: 0, separator: '.', delimiter: ',')%></h2>
			<h4>User Likes</h4>
			</div>
		</div>			
		<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
			<div class="counting_sl">
			<i class="fa fa-retweet"></i>
			<h2 class="counter"><%= number_with_precision($stats[:retweets], precision: 0, separator: '.', delimiter: ',')%></h2>
			<h4>User Retweets</h4>
			</div>
		</div>	
		<div class="chart_sec">
			<!--Table and divs that hold the pie charts-->
    		<table class="rows">
      		<tr>
        		<td><div id="veracityChart"></div></td>
        		<td><div id="sentimentChart"></div></td>
      		</tr>
    		</table>
		</div>
    <div id="geochart-colors" class="chart_sec"></div>
	</div>	
</div>
</section>
<!-- End Stat Section -->

app/views/pages/home.html.erb
<% content_for :body_class, 'home_body' %>

<div class="home">
  <div class="container">
    <%= image_tag("logo_white.svg", class: "logo_home") %>
    <h1>Twitter Fact Checker</h1>
    <h4>Twitter fact checker app prototype</h4>

    <%= form_tag action: "search_tweets"%>
    <div class="search-elem search-container row">
      <div class="search-elem search-input col-lg-10"><%= text_field_tag "keywords", "", placeholder:"Search new tweets", class:"search-elem" , id:"keyword_input" , autocomplete:"off"%></div>
      <div class="search-elem search-submit col-lg-2">
        <%= submit_tag "" , class:"search-elem"%>
        <div class="search-icon"><i class="fa fa-search" aria-hidden="true"></i></div>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<%= provide(:title, "Homepage") %>

<%= render "layouts/header_index" %>

<!-- start slider Section -->
<div id="myCarousel" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag('slider1.jpg') %>
      <div class="container">
        <div class="carousel-caption">
          <h1>We are twitter fact checker</h1>
          <p>tool for fact-checking with twitter's data</p>
        </div>
      </div>
    </div>
    <div class="item">
      <%= image_tag('slider2.jpg') %>
      <div class="container">
        <div class="carousel-caption">
          <h1>We are Creative</h1>
          <p>elegant web interface with responsive design</p>
        </div>
      </div>
    </div>
    <div class="item">
      <%= image_tag('slider3.jpg') %>
      <div class="container">
        <div class="carousel-caption">
          <h1>We Have Great Team</h1>
          <p>team of designer and developer students</p>
        </div>
      </div>
    </div>
  </div>

  <div id='search-box'>
    <form method='post' action='<%= get_path_for_search %>' id='search-form2' target='_top'>
      <%= text_field_tag 'keywords', '', id: 'search-text', placeholder:'Wanna check a fact ?', autocomplete: 'off', required: 'true' %>
      <button id='search-button' type='submit'>
        <span>Check</span>
      </button>
    </form>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <i class="glyphicon glyphicon-chevron-left"></i>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <i class="glyphicon glyphicon-chevron-right"></i>
  </a>
</div>
<!-- End slider Section -->

<!-- start about Section -->
<section id="abt_sec">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs12 ">
				<div class="title_sec">
					<h1 style="color: #fff">ABOUT</h1>
					<h2 style="color: #fff">WE’RE TWITTER FACTCHECKER GROUP FROM INSA RENNES</h2>
				</div>
			</div>
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs12 ">
				<div class="abt">
					<p>We are 5 students from the Computer Science faculty of INSA Rennes, France. This is our production website for the Practical Study subject. The idea is to build a web application that processes and verifies the veracity of an information stream via Twitter. The project is under the direction of Mr. Alexandru Costan, researcher at INSA Rennes. We divided the team into two subgroups, one for data processing (back-end) and the other for interface design (front-end). Our application is developed with Ruby on Rails platform, Twitter API and responsive design rules.</p>
				</div>
			</div>
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs12 ">
				<div class="text-center">
					<a href="#myCarousel" class="btn btn-warning page-scroll" role="button">Try now</a>
					<a href="https://www.youtube.com/watch?v=-7N6TmfLEvg" target="_blank" class="btn btn-success" role="button">Watch video</a>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End About Section -->

<!-- start our team Section -->
<section id="tm_sec">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs12 ">
				<div class="title_sec">
					<h1>Our Team</h1>
					<h2>WE’RE TWITTER FACTCHECKER GROUP FROM INSA RENNES</h2>
				</div>
			</div>
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs12">
				<div class="all_team">
					<div class="sngl_team">
            <%= image_tag("team/mem1.jpg") %>
						<h3> Ngoc Minh Quan Pham <span>Designer</span></h3>
						<p>3rd year Big Data student</p>
					</div>
					<div class="sngl_team">
            <%= image_tag("team/mem2.jpg") %>
						<h3>Jordhan Madec <span> Developer </span></h3>
						<p>3rd year Big Data student</p>
					</div>
					<div class="sngl_team">
            <%= image_tag("team/mem3.jpg") %>
						<h3> Hugo Vincent <span>  Developer  </span></h3>
						<p>3rd year Security student</p>
					</div>
					<div class="sngl_team">
            <%= image_tag("team/mem4.jpg") %>
						<h3>Haris Pasic<span> Developer </span></h3>
						<p>3rd year Security student</p>
					</div>
					<div class="sngl_team">
            <%= image_tag("team/mem5.jpg") %>
						<h3>Jordan Le Bongoat<span> Designer </span></h3>
						<p>3rd year Security student</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End our team Section -->

<!-- start portfolio Section -->
<section id="photo_sec">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs12 ">
				<div class="title_sec">
					<h1>Our Photos</h1>
					<h2>WE’RE TWITTER FACTCHECKER GROUP FROM INSA RENNES</h2>
				</div>
			</div>
			<div class="col-lg-12">
				<div class="portfolio-filter text-uppercase text-center">
          <ul class="filter">
          <li class="active" data-filter="*">All</li>
          <li data-filter=".screenshot">Screenshot</li>
          <li data-filter=".teamwork">Teamwork</li>
          <li data-filter=".product">Product</li>
          </ul>
				</div>

				<div class="all-portfolios">
          <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12 ">
            <div class="single-portfolio screenshot">
              <img class="img-responsive" src="<%= image_path('portfolio/p_02.jpg') %>" alt="">
            </div>
          </div>
          <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12 ">
            <div class="single-portfolio screenshot">
              <img class="img-responsive" src="<%= image_path('portfolio/p_08.jpg') %>" alt="">
            </div>
          </div>
          <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12 ">
            <div class="single-portfolio teamwork">
              <img class="img-responsive" src="<%= image_path('portfolio/p_03.jpg') %>" alt="">
            </div>
          </div>
          <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12 ">
            <div class="single-portfolio teamwork">
              <img class="img-responsive" src="<%= image_path('portfolio/p_04.jpg') %>" alt="">
            </div>
          </div>
          <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12 ">
            <div class="single-portfolio teamwork">
              <img class="img-responsive" src="<%= image_path('portfolio/p_05.jpg') %>" alt="">
            </div>
          </div>
          <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12 ">
            <div class="single-portfolio teamwork">
              <img class="img-responsive" src="<%= image_path('portfolio/p_09.jpg') %>" alt="">
            </div>
          </div>
          <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12 ">
            <div class="single-portfolio product">
              <img class="img-responsive" src="<%= image_path('portfolio/p_06.jpg') %>" alt="">
            </div>
          </div>
          <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12 ">
            <div class="single-portfolio product">
              <img class="img-responsive" src="<%= image_path('portfolio/p_07.jpg') %>" alt="">
            </div>
          </div>
          <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12 ">
            <div class="single-portfolio product">
              <img class="img-responsive" src="<%= image_path('portfolio/p_10.jpg') %>" alt="">
            </div>
          </div>
          <div class="col-sm-12 col-lg-12 col-md-12 col-xs-12 ">
            <div class="single-portfolio product">
              <img class="img-responsive" src="<%= image_path('portfolio/p_01.jpg') %>" alt="">
            </div>
          </div>
				</div>
			</div>
				<div class="post_btn">
					<div class="hover_effect_btn" id="hover_effect_btn">
						<a href="#hover_effect_btn" data-hover="view more post"><span>view more post</span></a>
					</div>
				</div>
			</div>
		</div>
</section>
<!-- End Portfolio Section -->

<!-- start our teastimonial Section -->
<section id="tstm_sec">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="all_tstm">
				<div class="clnt_tstm">
					<div class="sngl_tstm">
						<i class="fa fa-quote-right"></i>
						<h3>Be sure we're right</h3>
						<p>Never state in a fact check anything of which we’re not certain.</p>
						<h6>- John Daniszewski</h6>
					</div>
				</div>

				<div class="clnt_tstm">
					<div class="sngl_tstm">
						<i class="fa fa-quote-right"></i>
						<h3>Prioritize items with relevance and importance</h3>
						<p>We can’t check every falsehood. Focus on things that matter.</p>
						<h6>- John Daniszewski</h6>
					</div>
				</div>
				<div class="clnt_tstm">
					<div class="sngl_tstm">
						<i class="fa fa-quote-right"></i>
						<h3>Keep items short</h3>
						<p>The lead should present the assertion that’s being checked, and quickly state what’s wrong with it.</p>
						<h6>- John Daniszewski</h6>
					</div>
				</div>
				<div class="clnt_tstm">
					<div class="sngl_tstm">
						<i class="fa fa-quote-right"></i>
						<h3>Stick to checking facts, rather than opinion</h3>
						<p>A person’s personal tastes and preferences might lie outside the mainstream, but as opinions they are not a topic for a fact check.</p>
						<h6>- John Daniszewski</h6>
					</div>
				</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End our teastimonial Section -->

<!-- start contact us Section -->
<section id="ctn_sec">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs12 ">
				<div class="title_sec">
					<h1>Contact Info</h1>
					<h2>WE’RE TWITTER FACTCHECKER GROUP FROM INSA RENNES</h2>
				</div>
			</div>
			<div class="col-sm-6">
				<div id="cnt_form">
					<form id="contact-form" class="contact" name="contact-form" method="post" action="send-mail.php">
						<div class="form-group">
						<input type="text" name="name" class="form-control name-field" required="required" placeholder="Your Name">
						</div>
						<div class="form-group">
							<input type="email" name="email" class="form-control mail-field" required="required" placeholder="Your Email">
						</div>
						<div class="form-group">
							<textarea name="message" id="message" required="required" class="form-control" rows="8" placeholder="Message"></textarea>
						</div>
						<div class="form-group">
							<button type="submit" class="btn btn-primary">Send</button>
						</div>
					</form>
				</div>
			</div>
			<div class="col-lg-6 col-md-6 col-sm-6">
				<div class="cnt_info">
					<ul>
						<li><i class="fa fa-map-marker"></i><p>20 Avenue des Buttes de Coesmes, 35043 Rennes Cedex</p></li>
						<li><i class="fa fa-envelope"></i><p>deptinfo@insa-rennes.fr</p></li>
						<li><i class="fa fa-phone"></i><p>+33 2 23 23 82 51</p></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End contact us Section -->

<!-- start Alliance Section -->
<section id="alnc_sec">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs12 ">
				<div class="title_sec">
					<h1>Our alliances</h1>
					<h2>WE’RE TWITTER FACTCHECKER GROUP FROM INSA RENNES</h2>
				</div>
			</div>
			<div class="col-lg-12 col-md-12 col-sm-12 col-xs12">
				<div class="al_clt">
					<div class="sngl_alnc">
            <%= link_to_image "alliance/twitter.png", "https://twitter.com/", target: "_blank" %>
					</div>
					<div class="sngl_alnc">
            <%= link_to_image "alliance/insa.png", "https://www.insa-rennes.fr/", target: "_blank" %>
					</div>
					<div class="sngl_alnc">
            <%= link_to_image "alliance/rails.png", "http://rubyonrails.org/", target: "_blank" %>
					</div>
					<div class="sngl_alnc">
            <%= link_to_image "alliance/bootstrap.png", "http://getbootstrap.com/", target: "_blank" %>
					</div>
					<div class="sngl_alnc">
            <%= link_to_image "alliance/jquery.png", "https://jquery.com/", target: "_blank" %>
					</div>
					<div class="sngl_alnc">
            <%= link_to_image "alliance/github.png", "https://github.com/", target: "_blank" %>
					</div>
					<div class="sngl_alnc">
            <%= link_to_image "alliance/slack.png", "https://slack.com/", target: "_blank" %>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End Alliance Section -->

app/views/pages/result.html.erb
<%= provide(:title, "Search Results") %>

<%= render "layouts/header_others" %>

<!-- start blog Section -->
<section id="blg_sec">
	<div class="container">
		<div class="row">
      <br/>
			<div class="title_sec">
				<h1>SEARCH RESULTS</h1>
				<h2>WE’RE TWITTER FACTCHECKER GROUP FROM INSA RENNES</h2>
			</div>

      <div class="well text-center">
        <h2>"<%= @raw_request %>" is </h2>
        <%= render_fact_result($stats[:true_count], $stats[:false_count]).html_safe %>
      </div>

			<div class="col-lg-8 col-md-8 col-sm-8" style="z-index: 2;">
        <% @tweet_list.each do |key, tweet| %>
          <div class="sngl_blg">
            <div class="post_info">
              <div class="user_name">
                <h2><%= tweet["user"]["name"] %></h2>
                <i class="fa fa-twitter"></i>
              </div>
              <div class="user_id">
                @<%= tweet["user"]["screen_name"] %>
              </div>
            </div>
            <div class="post_content">
              <p class='tweet_text'><%= tweet["text"] %></p>
              <div class="row">
                  <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <span class="pull-left">
                      <i class="fa fa-heart"></i>&nbsp;Favorites : <%= tweet["favorite_count"] %>
                    </span>
                    <span class="pull-left">
                      <i class="fa fa-retweet"></i>&nbsp;Retweets : <%= tweet["retweet_count"] %>
                    </span>
                  </div>
                  <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                    <a href='https://twitter.com/<%= tweet["user"]["screen_name"] %>' target='_blank' data-toggle="popover"
                       title='<%= tweet["user"]["name"] %>'
                       data-content='Go to https://twitter.com/<%= tweet["user"]["screen_name"] %>'>
                      <i class="fa fa-long-arrow-right"></i> See more
                    </a>
                  </div>
                </div>
            </div>
          </div>
        <% end %>
			</div>				
			
			<div class="col-lg-4 col-md-4 col-sm-4" style="z-index: 1;">
				<div class="sidebar">						
					<div class="search_widget">
            <form method="post" action="<%= get_path_for_search %>">
              <%= text_field_tag 'keywords', '', id: 'sr_bx', placeholder:'Check a new fact ...', required: 'true', autocomplete: 'off' %>
              <button id='sr_bx_submit_btn' type='submit'>Go</button>
            </form>
					</div>				
					<div class="widget">
						<h2>fact information</h2>
						<div class="title_br"></div>
						<ul>
							<li>Matching tweets : <%= @nbTweets %></li>
							<li>Accuracy class :
                <% if $stats[:true_count] > $stats[:false_count] %>
                    Accurate
                <% else %>
                    <% if $stats[:true_count] < $stats[:false_count] %>
                      Fake
                    <% else %>
                      Unknown
                    <% end %>
                <%end%>
              </li>
							<li>Sentimental class :
                <% case [$stats[:positive_count], $stats[:neutral_count], $stats[:negative_count]].max() %>
                <% when $stats[:neutral_count] %>
                    Neutral
                <% when $stats[:positive_count] %>
                    Positive
                <% when $stats[:negative_count] %>
                    Negative
                <% else %>
                    Indeterminate
                <%end%>
              </li>
              <li>Favorites count: <%= $stats[:favs] %></li>
              <li>Retweets count: <%= $stats[:retweets] %></li>
						</ul>
					</div>							
					<div class="widget">
						<h2>keywords</h2>
						<div class="title_br"></div>
						<ul class="tag">
              <% @raw_request.scan(/[\w\-']+/) {|tag| %>
                  <li><a href="#"><%= tag %></a></li>
              <% } %>
						</ul>
					</div>
          <div class="widget">
            <button type="button" class="btn btn-sky text-uppercase btn-lg">
              <a href="<%= pages_charts_path %>">
                <strong>SEE GRAPHIC CHARTS&emsp;<i class="fa fa-pie-chart" aria-hidden="true"></i></strong>
              </a>
            </button>
          </div>
        </div>
			</div>
		</div>
	</div>
</section>
<!-- end Blog Section -->

app/views/pages/search_tweets.html.erb
<% content_for :body_class, 'search_tweets_body' %>

<header>
  <div class="container">
    <div class="header_logo">
      <%= image_tag("logo_white.svg")%>
    </div>
    <div class="header_title">
      <h1>Twitter Fact Checker</h1>
      <h4>Twitter fact checker app prototype</h4>
    </div>

    <%= form_tag action: "search_tweets"%>
      <div class="search-elem search-container row">
        <div class="search-elem search-input col-lg-10"><%= text_field_tag "keywords", "", placeholder:"Search new tweets", class:"search-elem" , id:"keyword_input" , autocomplete:"off"%></div>
        <div class="search-elem search-submit col-lg-2">
          <%= submit_tag "" , class:"search-elem"%>
          <div class="search-icon"><i class="fa fa-search" aria-hidden="true"></i></div>
        </div>
      </div>
  </div>
</header>

<div class="container">
  <div>
      <h2><%= @nbTweets %> tweets found</h2>
      <p id="keywords_list">Keywords : <b><%= @keywords %></b></p>

      <h2>True: <%= @true_class[:score] %></h2>
      <h2>False: <%= @false_class[:score] %></h2>

      <br>

      <div class="row">
        <% $stats.each do |label,value| %>
          <div class="col-lg-2">
            <p>
              <b><%= label.to_s %>: </b>
              <%= value %>
            </p>
          </div>
        <%end%>
      </div>


      <div class="row">
        <p>Nombre de tweet par classe de ressemblance syntaxique</p>
        <% $classe.each do |i| %>
          <div class="col-lg-2">
            <p>
              <b><%= i.count %> </b>
            </p>
          </div>
        <%end%>
      </div>

      <%= i=0 %>
      <% @tweet_list.each do |key,tweet| %>
        <div class="tweet">
          <h4><a href="<%= tweet["user"]["url"] %>" target="_blank">@<%= tweet["user"]["screen_name"] %></a></h4>
          <p class="tweet_content"><%= tweet["text"] %></p>
          <p class="tweet_content"><%= tweet["cleaned_text"] %></p>
          <p class="tweet_content"><b>Negatif/Positif : </b><%= tweet["negatif"] %></p>
          <% if(i+1<@nbTweets)%>
          <p class="tweet_content"><b>Score avec le tweet d'après : </b><%= @matrice_score[i][1+i]["score"] %></p>
          <p class="tweet_content"><b>Class avec le tweet d'après : </b><%= @matrice_score[i][1+i]["value"] %></p>
          <%end%>
          <p class="tweet_content"><b>Sentimental class : </b><%= tweet["sentimental_class"] %>&emsp;&emsp;<b>Sentimental score : </b><%= tweet["sentimental_score"] %> </p>
           <p class="tweet_content"><b>Poids : </b><%= tweet["weight"] %></p>
          <p><b><i class="fa fa-heart" aria-hidden="true"></i>&nbsp;Favorites : </b><%= tweet["favorite_count"] %>
  	     <b>&emsp;&emsp;<i class="fa fa-retweet" aria-hidden="true"></i>&nbsp;Retweets : </b><%= tweet["retweet_count"] %></p>
        </div>
        <%= i+=1 %>
      <%end%>
  </div>
</div>