config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  post 'pages/home'
  get 'pages/search_tweets'
  post 'pages/search_tweets'
  get 'pages/index'
  get 'pages/result'
  post 'pages/result'
  get 'pages/charts'
  post 'pages/charts'

   root 'pages#index'

end

app/views/layouts/_footer.html.erb
<!-- start footer Section -->
<footer id="ft_sec">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="ft">
          <ul>
            <li><a href="https://www.facebook.com/QuanDC" target="_blank"><i class="fa fa-facebook"></i></a></li>
            <li><a href="https://twitter.com/quandc176" target="_blank"><i class="fa fa-twitter"></i></a></li>
            <li><a href="" target="_blank"><i class="fa fa-linkedin"></i></a></li>
            <li><a href="https://github.com/JordhanMadec/factchecking" target="_blank"><i class="fa fa-github"></i></a></li>
          </ul>
        </div>
        <ul class="copy_right">
          <li>&copy; TWITTER FACT CHECKER - INSA RENNES - 2017</li>
          <li>Follow Us on Social Media !</li>
        </ul>
      </div>
    </div>
  </div>
</footer>
<!-- End footer Section -->

app/views/layouts/_header_index.html.erb
<!-- Start Header Section -->
<header class="main_menu_sec navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
        <div class="lft_hd">
          <%= link_to_image "logo.svg", root_path %>
        </div>
      </div>
      <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
        <div class="rgt_hd">
          <div class="main_menu">
            <nav id="nav_menu">
              <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <div id="navbar">
                <%= render 'layouts/search_form' %>
                <ul class="pull-right">
                  <li><%= link_to "Home", pages_index_path, class: "page-scroll" %></li>
                  <li><a href="#">About <i class="fa fa-angle-down"></i></a>
                    <ul>
                      <li><a class="page-scroll" href="#abt_sec">Our Project</a></li>
                      <li><a class="page-scroll" href="#tm_sec">Our Team</a></li>
                      <li><a class="page-scroll" href="#photo_sec">Our Photos</a></li>
                      <li><a class="page-scroll" href="#alnc_sec">Our Alliances</a></li>
                      <li><a class="page-scroll" href="#ctn_sec">Contact Us</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- End Header Section -->

app/views/layouts/_header_others.html.erb
<!-- Start Header Section -->
<header class="main_menu_sec navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
        <div class="lft_hd">
          <%= link_to_image "logo.svg", root_path %>
        </div>
      </div>
      <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
        <div class="rgt_hd">
          <div class="main_menu">
            <nav id="nav_menu">
              <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <div id="navbar">
                <%= render 'layouts/search_form' %>
                <ul class="pull-right">
                  <li><%= link_to "Home", pages_index_path, class: "page-scroll" %></li>
                  <li><a href="#">About <i class="fa fa-angle-down"></i></a>
                    <ul>
                      <li><a class="page-scroll" href="<%= pages_index_path %>#abt_sec">Our Project</a></li>
                      <li><a class="page-scroll" href="<%= pages_index_path %>#tm_sec">Our Team</a></li>
                      <li><a class="page-scroll" href="<%= pages_index_path %>#photo_sec">Our Photos</a></li>
                      <li><a class="page-scroll" href="<%= pages_index_path %>#alnc_sec">Our Alliances</a></li>
                      <li><a class="page-scroll" href="<%= pages_index_path %>#ctn_sec">Contact Us</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- End Header Section -->

app/views/layouts/_javascripts_tag.html.erb
<%= javascript_include_tag 'application' %>

<!-- Use of Bootstrap popover -->
<script type="text/javascript">
    $(document).ready(function(){
        $('[data-toggle="popover"]').popover({
            placement: 'bottom',
            html: true,
            trigger: 'hover',
            container: 'body'
        });
    });
</script>

<!-- Google charts API scripts -->
<script type="text/javascript">
    google.charts.load('current', {packages: ['corechart']});
    google.charts.setOnLoadCallback(drawVeracityChart);
    google.charts.setOnLoadCallback(drawSentimentChart);

    function drawVeracityChart() {
        // Define the chart to be drawn.
        var data = google.visualization.arrayToDataTable([
            ['Veracity Class', 'Points'],
            ['Accurate',  <%= $stats[:true_count] %>],
            ['Fake',  <%= $stats[:false_count] %>]
        ]);

        var options = {
            title: 'VERACITY CLASS',
            pieHole: 0.28,
            slices: [{color: '#67BCDB'}, {color: '#B71427'}],
            fontSize: 18
        };

        // Instantiate and draw the chart.
        var chart = new google.visualization.PieChart(document.getElementById('veracityChart'));
        chart.draw(data, options);
    }

    function drawSentimentChart() {
        // Define the chart to be drawn.
        var data = google.visualization.arrayToDataTable([
            ['Sentiment Class', 'Points'],
            ['Positive',  <%= $stats[:positive_count] %>],
            ['Negative',  <%= $stats[:negative_count] %>],
            ['Neutral',   <%= $stats[:neutral_count] %>]
        ]);

        var options = {
            title: 'SENTIMENT CLASS',
            pieHole: 0.28,
            slices: [{color: '#118C4E'}, {color: '#e41713'}, {color: '#ffb01f'}],
            fontSize: 18
        };

        // Instantiate and draw the chart.
        var chart = new google.visualization.PieChart(document.getElementById('sentimentChart'));
        chart.draw(data, options);
    }
</script>

<script type="text/javascript">
    google.charts.load('current', {'packages':['geochart']});
    google.charts.setOnLoadCallback(drawRegionsMap);

    function drawRegionsMap() {
        var data = google.visualization.arrayToDataTable([
            ['Region Code', 'Continent', 'Tweets'],
            ['142', 'Asia', <%= $stats[:asia] %>],
            ['150', 'Europe', <%= $stats[:europe] %>],
            ['019', 'Americas', <%= $stats[:usa] + $stats[:south_america] %>],
            ['002', 'Africa', <%= $stats[:africa] %>]
        ]);

        var options = {
            resolution: "continents",
            colorAxis: {colors: ['#00a742', '#c71a20']},
            backgroundColor: '#81d4fa',
            datalessRegionColor: '#f8bbd0',
            defaultColor: '#f5f5f5',
        };

        var chart = new google.visualization.GeoChart(document.getElementById('geochart-colors'));
        chart.draw(data, options);
    };
</script>

<!-- Google Map js -->
<script>
    function initialize() {
        var mapOptions = {
            zoom: 14,
            scrollwheel: false,
            center: new google.maps.LatLng(48.120306, -1.634211)
        };
        var map = new google.maps.Map(document.getElementById('googleMap'),
            mapOptions);
        var marker = new google.maps.Marker({
            position: map.getCenter(),
            animation:google.maps.Animation.BOUNCE,
            icon: '/assets/map-marker.png',
            map: map
        });
    }
    google.maps.event.addDomListener(window, 'load', initialize);
</script>

<script type="text/javascript">
    $(document).ready(function(){
        $('.show_hide').showHide({
            speed: 1000,  // speed you want the toggle to happen
            easing: 'swing',  // the animation effect you want. Remove this line if you dont want an effect and if you haven't included jQuery UI
            changeText: 1, // if you dont want the button text to change, set this to 0
            showText: 'View',// the button text to show when a div is closed
            hideText: 'Close' // the button text to show when a div is open
        });
    });
</script>

<script>
    jQuery(document).ready(function( $ ) {
        $('.counter').counterUp({
            delay: 10,
            time: 1300
        });
    });
</script>

<script>
    //Hide Overflow of Body on DOM Ready //
    $(document).ready(function(){
        $("body").css("overflow", "hidden");
    });

    // Show Overflow of Body when Everything has Loaded
    $(window).load(function(){
        $("body").css("overflow", "visible");
        var nice=$('html').niceScroll({
            cursorborder:"5",
            cursorcolor:"#00AFF0",
            cursorwidth:"4px",
            boxzoom:true,
            autohidemode:true
        });
    });
</script>

<script type="text/javascript">
  // Highlight keywords in tweet contents
    $(document).ready(function() {
       var keywords_list = $(".tag > li > a").map(function() { return $(this).text(); }).get();
       var options = {
           element: "span",
           className: "keyword",
           synonyms: {
               "dont": "do not",
               "don't": "do not",
               "wont": "will not",
               "won't": "will not",
               "isn't": "is not",
               "aren't": "are not",
               "doesn't": "does not",
               "wouldn't": "would not",
               "'ve": "have",
               "haven't": "have not",
               "hasn't": "has not",
               "didn't": "did not",
               "i'll": "i will",
               "you'll": "you will",
               "he'll": "he will",
               "she'll": "she will",
               "it'll": "it will",
               "we'll": "we will",
               "they'll": "they will"
           }
       };
       $(".tweet_text").mark(keywords_list, options);
    });
</script>

app/views/layouts/_map.html.erb
<!-- start located map Section -->
<section id="ltd_map_sec">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="map">
          <h1>locate THE MAP</h1><a href="#slidingDiv" class="show_hide" rel="#slidingDiv"><i class="fa fa-angle-up"></i></a>
          <div id="slidingDiv">
            <div class="map_area">
              <div id="googleMap" style="width:100%;height:300px;"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End located map  Section -->

app/views/layouts/_preloader.html.erb
<!-- start preloader -->
<div id="loader-wrapper">
  <div id="loader"></div>
</div>
<!-- end preloader -->
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

app/views/layouts/_search_form.html.erb
<!-- SEARCH FORM -->
<div id="search-form" class="pull-right">
  <form method="post" action="<%= get_path_for_search %>">
    <%= text_field_tag 'keywords', '', placeholder:'Search', required: 'true', autocomplete: 'off' %>
  </form>
</div><!-- SEARCH FORM -->

app/views/layouts/_stylesheets_tag.html.erb
<%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Lato:400,300,700', media: 'all', type: 'text/css' %>
<%= stylesheet_link_tag 'http://fonts.googleapis.com/icon?family=Material+Icons', media: 'all', type: 'text/css' %>
<%= stylesheet_link_tag 'normalize', media: 'all', type: 'text/css' %>
<%= stylesheet_link_tag 'main', media: 'all', type: 'text/css' %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'bootstrap-theme.min', media: 'all', type: 'text/css' %>
<%= stylesheet_link_tag 'owl.carousel', media: 'all', type: 'text/css' %>
<%= stylesheet_link_tag 'responsive', media: 'all', type: 'text/css' %>
<%= stylesheet_link_tag 'button', media: 'all', type: 'text/css' %>
<%= stylesheet_link_tag 'style', media: 'all', type: 'text/css' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title><%= make_title(yield(:title)) %></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag 'icon.png', rel: 'icon', type: 'image/png' %>

    <!--[if lt IE 9]><%= javascript_include_tag 'html5shiv' %>
    <%= javascript_include_tag 'respond.min' %><![endif]-->
    <!-- Place favicon.ico in the root directory -->

    <%= render "layouts/stylesheets_tag" %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js", type: "text/javascript" %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyBvQYoUZvqPTL8LFTFonv8WqZOZ2mGSf8o" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/preloader" %>

    <%= yield %>

    <%= render "layouts/map" %>
    <%= render "layouts/footer" %>
    <%= render "layouts/javascripts_tag" %>
  </body>
</html>